In [157]:
import pandas as pd

Problems
Problem 1. Explore the Dataset
Load the Online Food Ordering Dataset into a Pandas DataFrame called df.
Display:
• First 5 rows
• Number of rows and columns
• Column names
• Data types of all columns

In [158]:
df = pd.read_csv("online food delivery dataset.csv")

# Q.1 print first 5 rows
print(df.head())

   Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income
1   24  Female         Single    Student  Below Rs.10000
2   22    Male         Single    Student  Below Rs.10000
3   22  Female         Single    Student       No Income
4   22    Male         Single    Student  Below Rs.10000

  Educational Qualifications  Family size Customer Type  latitude  longitude  \
0              Post Graduate            4      Frequent   12.9766    77.5993
1                   Graduate            3       Regular   12.9770    77.5773
2              Post Graduate            3       Regular   12.9551    77.6593
3                   Graduate            6      Frequent   12.9473    77.5616
4              Post Graduate            4      Frequent   12.9850    77.5533

   Pin code Output   Feedback Unnamed: 13
0    560001    Yes   Positive         Yes
1    560009    Yes   Positive         Yes
2    560017    Yes  Negative          Yes
3    560019    Yes   Positive         Yes
4    560010    Yes   Positive         Yes

In [159]:
# Q.2 Print total no. of rows and coloumns
print(df.shape)

(388, 14)

In [160]:
# Q.3 Column names 
print(df.columns)

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Customer Type',
       'latitude', 'longitude', 'Pin code', 'Output', 'Feedback',
       'Unnamed: 13'],
      dtype='object')

In [161]:
# Q.4 Data type of all columns
print(df.dtypes)

Age                             int64
Gender                         object
Marital Status                 object
Occupation                     object
Monthly Income                 object
Educational Qualifications     object
Family size                     int64
Customer Type                  object
latitude                      float64
longitude                     float64
Pin code                        int64
Output                         object
Feedback                       object
Unnamed: 13                    object
dtype: object

Problem 2. Customer Age Analysis
Using the DataFrame, determine:
• Average age of the customers
• Minimum age
• Maximum age
• Number of male customers
• Number of female customers

In [162]:
# 1) Average age of the customers 
print("Average age:", df["Age"].mean() )

Average age: 24.628865979381445

In [163]:
#  2) Minimum age
print("Min Age:",df["Age"].min())

Min Age: 18

In [164]:
# 3) Maximum age
print("Maximum age:",df["Age"].max())

Maximum age: 33

In [165]:
# 4) No. of Male Customers 
print("No. of male customer: ",(df["Gender"] == "Male").sum())

No. of male customer:  222

In [166]:
# 5) No. of Female Customers 
print("No. of Female customer: ",(df["Gender"] == "Female").sum())

No. of Female customer:  166

Problem 3. Filtering Customers
Find all customers who satisfy both conditions:
• Age is greater than 25
• Occupation is Employee
Display the following columns:
• Age
• Gender
• Occupation
• Monthly Income
1

In [167]:
# 1) Filtering and display soloumns age gender occupation
df[(df["Age"]>25) & (df["Occupation"] == "Employee")]

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,Regular,12.9299,77.6848,560103,Yes,Positive,Yes
16,28,Female,Single,Employee,25001 to 50000,Post Graduate,2,Regular,12.9783,77.6408,560038,Yes,Positive,Yes
58,31,Male,Married,Employee,More than 50000,Ph.D,5,Frequent,12.9119,77.6446,560102,Yes,Positive,Yes
90,27,Female,Prefer not to say,Employee,25001 to 50000,Post Graduate,5,Frequent,13.0289,77.5400,560022,No,Positive,No
98,26,Male,Married,Employee,25001 to 50000,Graduate,5,Frequent,12.9579,77.6309,560007,No,Positive,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive,Yes
371,28,Male,Married,Employee,25001 to 50000,Graduate,3,Regular,12.9369,77.6407,560095,Yes,Positive,Yes
375,26,Female,Married,Employee,Below Rs.10000,Graduate,6,Frequent,12.9859,77.6713,560093,No,Negative,No
377,31,Male,Prefer not to say,Employee,Below Rs.10000,Graduate,1,New,12.9866,77.4904,560091,No,Negative,No
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,Regular,12.9299,77.6848,560103,Yes,Positive,Yes

In [168]:
df[(df["Age"]>25) & (df["Occupation"] == "Employee")][["Age", "Gender","Occupation", "Monthly Income"]]

     Age  Gender Occupation   Monthly Income
5     27  Female   Employee  More than 50000
16    28  Female   Employee   25001 to 50000
58    31    Male   Employee  More than 50000
90    27  Female   Employee   25001 to 50000
98    26    Male   Employee   25001 to 50000
..   ...     ...        ...              ...
369   30    Male   Employee  More than 50000
371   28    Male   Employee   25001 to 50000
375   26  Female   Employee   Below Rs.10000
377   31    Male   Employee   Below Rs.10000
380   27  Female   Employee  More than 50000

[73 rows x 4 columns]