In [157]:
import pandas as pd

Problems
Problem 1. Explore the Dataset
Load the Online Food Ordering Dataset into a Pandas DataFrame called df.
Display:
• First 5 rows
• Number of rows and columns
• Column names
• Data types of all columns

In [158]:
df = pd.read_csv("online food delivery dataset.csv")

# Q.1 print first 5 rows
print(df.head())

   Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income
1   24  Female         Single    Student  Below Rs.10000
2   22    Male         Single    Student  Below Rs.10000
3   22  Female         Single    Student       No Income
4   22    Male         Single    Student  Below Rs.10000

  Educational Qualifications  Family size Customer Type  latitude  longitude  \
0              Post Graduate            4      Frequent   12.9766    77.5993
1                   Graduate            3       Regular   12.9770    77.5773
2              Post Graduate            3       Regular   12.9551    77.6593
3                   Graduate            6      Frequent   12.9473    77.5616
4              Post Graduate            4      Frequent   12.9850    77.5533

   Pin code Output   Feedback Unnamed: 13
0    560001    Yes   Positive         Yes
1    560009    Yes   Positive         Yes
2    560017    Yes  Negative          Yes
3    560019    Yes   Positive         Yes
4    560010    Yes   Positive         Yes

In [159]:
# Q.2 Print total no. of rows and coloumns
print(df.shape)

(388, 14)

In [160]:
# Q.3 Column names 
print(df.columns)

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'Customer Type',
       'latitude', 'longitude', 'Pin code', 'Output', 'Feedback',
       'Unnamed: 13'],
      dtype='object')

In [161]:
# Q.4 Data type of all columns
print(df.dtypes)

Age                             int64
Gender                         object
Marital Status                 object
Occupation                     object
Monthly Income                 object
Educational Qualifications     object
Family size                     int64
Customer Type                  object
latitude                      float64
longitude                     float64
Pin code                        int64
Output                         object
Feedback                       object
Unnamed: 13                    object
dtype: object

Problem 2. Customer Age Analysis
Using the DataFrame, determine:
• Average age of the customers
• Minimum age
• Maximum age
• Number of male customers
• Number of female customers

In [162]:
# 1) Average age of the customers 
print("Average age:", df["Age"].mean() )

Average age: 24.628865979381445

In [163]:
#  2) Minimum age
print("Min Age:",df["Age"].min())

Min Age: 18

In [164]:
# 3) Maximum age
print("Maximum age:",df["Age"].max())

Maximum age: 33

In [165]:
# 4) No. of Male Customers 
print("No. of male customer: ",(df["Gender"] == "Male").sum())

No. of male customer:  222

In [166]:
# 5) No. of Female Customers 
print("No. of Female customer: ",(df["Gender"] == "Female").sum())

No. of Female customer:  166

Problem 3. Filtering Customers
Find all customers who satisfy both conditions:
• Age is greater than 25
• Occupation is Employee
Display the following columns:
• Age
• Gender
• Occupation
• Monthly Income
1

In [167]:
# 1) Filtering and display soloumns age gender occupation
df[(df["Age"]>25) & (df["Occupation"] == "Employee")]

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,Regular,12.9299,77.6848,560103,Yes,Positive,Yes
16,28,Female,Single,Employee,25001 to 50000,Post Graduate,2,Regular,12.9783,77.6408,560038,Yes,Positive,Yes
58,31,Male,Married,Employee,More than 50000,Ph.D,5,Frequent,12.9119,77.6446,560102,Yes,Positive,Yes
90,27,Female,Prefer not to say,Employee,25001 to 50000,Post Graduate,5,Frequent,13.0289,77.5400,560022,No,Positive,No
98,26,Male,Married,Employee,25001 to 50000,Graduate,5,Frequent,12.9579,77.6309,560007,No,Positive,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive,Yes
371,28,Male,Married,Employee,25001 to 50000,Graduate,3,Regular,12.9369,77.6407,560095,Yes,Positive,Yes
375,26,Female,Married,Employee,Below Rs.10000,Graduate,6,Frequent,12.9859,77.6713,560093,No,Negative,No
377,31,Male,Prefer not to say,Employee,Below Rs.10000,Graduate,1,New,12.9866,77.4904,560091,No,Negative,No
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,Regular,12.9299,77.6848,560103,Yes,Positive,Yes

In [168]:
df[(df["Age"]>25) & (df["Occupation"] == "Employee")][["Age", "Gender","Occupation", "Monthly Income"]]

     Age  Gender Occupation   Monthly Income
5     27  Female   Employee  More than 50000
16    28  Female   Employee   25001 to 50000
58    31    Male   Employee  More than 50000
90    27  Female   Employee   25001 to 50000
98    26    Male   Employee   25001 to 50000
..   ...     ...        ...              ...
369   30    Male   Employee  More than 50000
371   28    Male   Employee   25001 to 50000
375   26  Female   Employee   Below Rs.10000
377   31    Male   Employee   Below Rs.10000
380   27  Female   Employee  More than 50000

[73 rows x 4 columns]

Problem 4. Occupation Analysis
Use groupby() to calculate the average age of customers for each occupation.
Display the result and determine which occupation has the highest average customer age.

In [169]:
# Occupation Analysis
df.groupby("Occupation")["Age"].mean()

Occupation
Employee          26.576271
House wife        30.333333
Self Employeed    26.388889
Student           22.811594
Name: Age, dtype: float64

In [170]:
## store the result by assigning it to a variable
result = df.groupby("Occupation")["Age"].mean()

In [171]:

print(result.idxmax())

House wife

Problem 5. Feedback Analysis
Determine the number of customers who gave each type of feedback.
Then calculate the percentage of customers who gave positive feedback.
Display the results clearly.

In [172]:
df["Feedback"].value_counts()

Feedback
Positive     317
Negative      71
Name: count, dtype: int64

In [173]:
# Feed back 
feedback_count = df["Feedback"].value_counts()

# Percentage of Positive Feedback
print("Positive: ",(df["Feedback"] == "Positive").sum() / len(df) * 100)

Positive:  81.70103092783505

Problem 6. Occupation and Feedback
Use Pandas to investigate the relationship between occupation and customer feedback.
Group the data by:
Occupation
Feedback
Calculate the number of customers in each group and display the result.

In [174]:
# Store it in Ans variable 
Ans = df.groupby(["Occupation","Feedback"]).size()

In [175]:
print(Ans)

Occupation      Feedback
Employee        Negative      33
                Positive      85
House wife      Negative       1
                Positive       8
Self Employeed  Negative      16
                Positive      38
Student         Negative      21
                Positive     186
dtype: int64

Problem 7. Create a Bank Account Class
Create a class called BankAccount.
The class should have the following attributes:
• account num
• owner
• balance
Use init () to initialize these attributes.
Create two different bank account objects and display their attributes.

In [176]:
# Create a class 
class BankAccount:
# Define a init method
    def __init__(self, account_num, owner, balance):
               self.account_num = account_num
               self.owner= owner
               self.balance = balance

# define a Deposite method here 
    def deposite(self, amount):
         self.balance += amount

# Define a Withrawal method 
    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            return True
        else:
            return False

# Define Str method 
    def __str__(self):
        return f"{self.account_num} | {self.owner}: ₹{self.balance}"

In [177]:
account1 = BankAccount(1,'Kunal', 1000)

print(account1.account_num)
print(account1.owner)
print(account1.balance)

1
Kunal
1000

In [178]:
account2 = BankAccount(2,'Pankaj', 500)

print(account2.account_num)
print(account2.owner)
print(account2.balance)

2
Pankaj
500

Problem 8. Bank Account Methods
Add the following methods to the BankAccount class:
• deposit()
• withdraw()
The deposit(amount) method should add the given amount to the account balance.
The withdraw(amount) method should subtract the given amount from the balance only when
sufficient balance is available.
Create an account and test both methods.

In [179]:
# method will be define in class 

# create a new account here
account3 = BankAccount(3,'Pratik',0) 

# test deposite
account3.deposite(3000)

# test withrawal
account3.withdraw(1000)

# check everything is okk or not 
print(account3.deposite)
print(account3.withdraw)
print(account3.balance)

<bound method BankAccount.deposite of <__main__.BankAccount object at 0x000002513BB4BB10>>
<bound method BankAccount.withdraw of <__main__.BankAccount object at 0x000002513BB4BB10>>
2000

Problem 9. Withdrawal Status
Modify the withdraw() method so that it returns:
• True when the withdrawal is successful.
• False when the withdrawal cannot be completed.
Test the method with:
• A valid withdrawal
• A withdrawal greater than the available balance
Display the returned values and the account balance.

In [180]:
# Test valid withdrawal
status1 = account3.withdraw(500)
print(status1)
print(account3.balance)

# Test withdrawal greater than available balance
status2 = account3.withdraw(5000)
print(status2)
print(account3.balance)

True
1500
False
1500

Problem 10. Display Account Details
Add a str () method to the BankAccount class.
When an account object is passed to print(), display its:
• Account number
• Owner
• Balance
Create an account and display it using:
print(account)

In [181]:
# I added str method on class 

# create a new account so we test the Str method
account4 = BankAccount(4, "Shraddha", 50)

# test the str is working or not 
print(account4)

4 | Shraddha: ₹50

Problem 11. Student Class
Create a class called Student.
The class should have the following attributes:
• name
• roll no
• marks
Create at least three Student objects.
Add a method called average marks() that returns the average of the student’s marks.
Display the average marks of each student.

In [182]:
# class of student 
class Student :
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

# Define a average marks method here
    def average_marks(self):
        return sum(self.marks) / len(self.marks)

In [183]:
# Create 3 student objects
Student1 = Student("Kunal", 13, [70, 65, 55])
Student2 = Student("Pankaj", 7, [80, 55, 84])
Student3 = Student("siddhi", 19, [65, 90, 63])

In [184]:
# Display average marks
print(Student1.name, Student1.average_marks())
print(Student2.name, Student2.average_marks())
print(Student3.name, Student3.average_marks())

Kunal 63.333333333333336
Pankaj 73.0
siddhi 72.66666666666667